name: closed_network
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  flutter_inset_shadow: ^2.0.3
  loading_animation_widget: ^1.2.0+4
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  animate_do: ^3.0.2
  flutter_svg: ^2.0.7
  path_provider: ^2.1.1
  record: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  awesome_snackbar_content: ^0.1.3
  like_button: ^2.0.5
  image_picker: ^1.1.2
  insta_like_button: ^0.1.1
  flutter_bloc:
  flutter_animate: ^4.2.0
  slide_to_act: ^2.0.2
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  flutter_easy_faq: ^1.0.1
  url_launcher: ^6.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
  web: true

  image: assets/splash.png
  image_dark: assets/splash.png

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  fullscreen: true

flutter_launcher_icons:
  image_path: "assets/splash.png"
  android: true
  ios: true
  web:
    generate: true
    background_color: "#000000" # black background
  background_color: "#000000"   # for Android & iOS
