name: closed_network
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  flutter_inset_shadow: ^2.0.3
  loading_animation_widget: ^1.2.0+4
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  animate_do: ^3.0.2 # Specify the version
  flutter_svg: ^2.0.7 # Specify the version
  path_provider: ^2.1.1 # Specify the version
  record: ^4.0.0 # Specify the version
  flutter_staggered_grid_view: ^0.7.0
  awesome_snackbar_content: ^0.1.3
  like_button: ^2.0.5
  image_picker: ^1.1.2
  insta_like_button: ^0.1.1
  flutter_bloc:
  flutter_animate: ^4.2.0
  slide_to_act: ^2.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

