// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfYpg71Kpku6Ewrl4gGXGaOkg4h-WcEHc',
    appId: '1:238881618624:web:4a45ce9aa1e7d81438cb25',
    messagingSenderId: '238881618624',
    projectId: 'closednetwork-01',
    authDomain: 'closednetwork-01.firebaseapp.com',
    storageBucket: 'closednetwork-01.firebasestorage.app',
    measurementId: 'G-RW1DB5ETCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ9QR5vuIw9Z8UYSKmRWWAmZ1HB2-q0jo',
    appId: '1:238881618624:android:0ae395180f160ff638cb25',
    messagingSenderId: '238881618624',
    projectId: 'closednetwork-01',
    storageBucket: 'closednetwork-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB10LVnZdSTmM-M1ySrEnTU8QVgvTkyYC0',
    appId: '1:238881618624:ios:b03e6b721e48288738cb25',
    messagingSenderId: '238881618624',
    projectId: 'closednetwork-01',
    storageBucket: 'closednetwork-01.firebasestorage.app',
    androidClientId: '238881618624-hlo90nku2n05ulv2oilo9vt7mt569h6e.apps.googleusercontent.com',
    iosClientId: '238881618624-irifhe0u7uk1cr3qpoe55bu226j0g0v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.closedNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB10LVnZdSTmM-M1ySrEnTU8QVgvTkyYC0',
    appId: '1:238881618624:ios:b03e6b721e48288738cb25',
    messagingSenderId: '238881618624',
    projectId: 'closednetwork-01',
    storageBucket: 'closednetwork-01.firebasestorage.app',
    androidClientId: '238881618624-hlo90nku2n05ulv2oilo9vt7mt569h6e.apps.googleusercontent.com',
    iosClientId: '238881618624-irifhe0u7uk1cr3qpoe55bu226j0g0v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.closedNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfYpg71Kpku6Ewrl4gGXGaOkg4h-WcEHc',
    appId: '1:238881618624:web:8cca3a1cf28ccf4638cb25',
    messagingSenderId: '238881618624',
    projectId: 'closednetwork-01',
    authDomain: 'closednetwork-01.firebaseapp.com',
    storageBucket: 'closednetwork-01.firebasestorage.app',
    measurementId: 'G-K50KC909R1',
  );
}
